/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: dev_data.proto */

#ifndef PROTOBUF_C_dev_5fdata_2eproto__INCLUDED
#define PROTOBUF_C_dev_5fdata_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _DevData DevData;
typedef struct _DevData__Param DevData__Param;
typedef struct _DevData__Device DevData__Device;


/* --- enums --- */


/* --- messages --- */

typedef enum {
  DEV_DATA__PARAM__VAL__NOT_SET = 0,
  DEV_DATA__PARAM__VAL_FVAL = 2,
  DEV_DATA__PARAM__VAL_IVAL = 3,
  DEV_DATA__PARAM__VAL_BVAL = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(DEV_DATA__PARAM__VAL)
} DevData__Param__ValCase;

/*
 *message for describing a single device parameter
 */
struct  _DevData__Param
{
  ProtobufCMessage base;
  char *name;
  DevData__Param__ValCase val_case;
  union {
    float fval;
    int32_t ival;
    protobuf_c_boolean bval;
  };
};
#define DEV_DATA__PARAM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dev_data__param__descriptor) \
    , (char *)protobuf_c_empty_string, DEV_DATA__PARAM__VAL__NOT_SET, {0} }


/*
 *message for describing a single device
 */
struct  _DevData__Device
{
  ProtobufCMessage base;
  char *type;
  char *uid;
  int32_t itype;
  /*
   *each device has some number of params
   */
  size_t n_params;
  DevData__Param **params;
};
#define DEV_DATA__DEVICE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dev_data__device__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0,NULL }


struct  _DevData
{
  ProtobufCMessage base;
  /*
   *this single field has information about all requested params of devices
   */
  size_t n_devices;
  DevData__Device **devices;
};
#define DEV_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dev_data__descriptor) \
    , 0,NULL }


/* DevData__Param methods */
void   dev_data__param__init
                     (DevData__Param         *message);
/* DevData__Device methods */
void   dev_data__device__init
                     (DevData__Device         *message);
/* DevData methods */
void   dev_data__init
                     (DevData         *message);
size_t dev_data__get_packed_size
                     (const DevData   *message);
size_t dev_data__pack
                     (const DevData   *message,
                      uint8_t             *out);
size_t dev_data__pack_to_buffer
                     (const DevData   *message,
                      ProtobufCBuffer     *buffer);
DevData *
       dev_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dev_data__free_unpacked
                     (DevData *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*DevData__Param_Closure)
                 (const DevData__Param *message,
                  void *closure_data);
typedef void (*DevData__Device_Closure)
                 (const DevData__Device *message,
                  void *closure_data);
typedef void (*DevData_Closure)
                 (const DevData *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor dev_data__descriptor;
extern const ProtobufCMessageDescriptor dev_data__param__descriptor;
extern const ProtobufCMessageDescriptor dev_data__device__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_dev_5fdata_2eproto__INCLUDED */
