/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: msg_enum.proto */

#ifndef PROTOBUF_C_msg_5fenum_2eproto__INCLUDED
#define PROTOBUF_C_msg_5fenum_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif




/* --- enums --- */

typedef enum _Msg {
  MSG__GAMEPAD_STATE = 0,
  MSG__DEVICE_DATA = 1,
  MSG__RUN_MODE = 2,
  MSG__CHALLENGE_DATA = 3,
  MSG__LOG = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MSG)
} Msg;

/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_msg_5fenum_2eproto__INCLUDED */
