/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: msg_enum.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "msg_enum.pb-c.h"
static const ProtobufCEnumValue msg__enum_values_by_number[5] =
{
  { "GAMEPAD_STATE", "MSG__GAMEPAD_STATE", 0 },
  { "DEVICE_DATA", "MSG__DEVICE_DATA", 1 },
  { "RUN_MODE", "MSG__RUN_MODE", 2 },
  { "CHALLENGE_DATA", "MSG__CHALLENGE_DATA", 3 },
  { "LOG", "MSG__LOG", 4 },
};
static const ProtobufCIntRange msg__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex msg__enum_values_by_name[5] =
{
  { "CHALLENGE_DATA", 3 },
  { "DEVICE_DATA", 1 },
  { "GAMEPAD_STATE", 0 },
  { "LOG", 4 },
  { "RUN_MODE", 2 },
};
const ProtobufCEnumDescriptor msg__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Msg",
  "Msg",
  "Msg",
  "",
  5,
  msg__enum_values_by_number,
  5,
  msg__enum_values_by_name,
  1,
  msg__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
