#!/usr/bin/env bash

# This executable file is meant to be run with a specific command like build, run, or test.
# You can make this file available everywhere by adding it to your PATH with
#   export PATH="$PATH:<path to runtime dir>"
# Examples:
#     runtime build                      (to run build.sh)
#     runtime run                        (to run run.sh)
#     runtime test integration/tc_68_2   (to run the automated test tc_68_2)

set -e  # Makes any errors exit the script

RUNTIME_DIR=$(dirname "${BASH_SOURCE[0]}")

cd $RUNTIME_DIR

case $1 in
    build)
        pushd shm_wrapper && make && popd
        pushd net_handler && make && popd
        pushd executor && make && popd
        pushd dev_handler && make && popd
        ;;

    run)
        scripts/run.sh
        ;;

    test)
        shift 1
        scripts/test.sh $@
        ;;

    format)
        ;;

    clean)
        pushd shm_wrapper && make clean && popd
        pushd net_handler && make clean && popd
        pushd executor && make clean && popd
        pushd dev_handler && make clean && popd
        pushd tests && make clean && popd
        rm -f /tmp/log-fifo
        rm -f /tmp/challenge.sock
        rm -f /tmp/ttyACM*
        ;;

    flash)
        shift 1
        scripts/flash.sh $@
        ;;

    *)
        commands="build run test format clean flash"
        printf "Runtime script needs another argument from:\n\n$commands\n\n"
        ;;
esac

