/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gamestate.proto */

#ifndef PROTOBUF_C_gamestate_2eproto__INCLUDED
#define PROTOBUF_C_gamestate_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
#error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
#error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _GameState GameState;


/* --- enums --- */

typedef enum _State {
    STATE__POISON_IVY = 0,
    STATE__DEHYDRATION = 1,
    STATE__HYPOTHERMIA_START = 2,
    STATE__HYPOTHERMIA_END = 3 PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(STATE)
} State;

/* --- messages --- */

struct _GameState {
    ProtobufCMessage base;
    State state;
};
#define GAME_STATE__INIT                                 \
    {                                                    \
        PROTOBUF_C_MESSAGE_INIT(&game_state__descriptor) \
        , STATE__POISON_IVY                              \
    }


/* GameState methods */
void game_state__init(GameState* message);
size_t game_state__get_packed_size(const GameState* message);
size_t game_state__pack(const GameState* message,
                        uint8_t* out);
size_t game_state__pack_to_buffer(const GameState* message,
                                  ProtobufCBuffer* buffer);
GameState*
game_state__unpack(ProtobufCAllocator* allocator,
                   size_t len,
                   const uint8_t* data);
void game_state__free_unpacked(GameState* message,
                               ProtobufCAllocator* allocator);
/* --- per-message closures --- */

typedef void (*GameState_Closure)(const GameState* message,
                                  void* closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor state__descriptor;
extern const ProtobufCMessageDescriptor game_state__descriptor;

PROTOBUF_C__END_DECLS


#endif /* PROTOBUF_C_gamestate_2eproto__INCLUDED */
