/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gamestate.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gamestate.pb-c.h"
void game_state__init(GameState* message) {
    static const GameState init_value = GAME_STATE__INIT;
    *message = init_value;
}
size_t game_state__get_packed_size(const GameState* message) {
    assert(message->base.descriptor == &game_state__descriptor);
    return protobuf_c_message_get_packed_size((const ProtobufCMessage*) (message));
}
size_t game_state__pack(const GameState* message,
                        uint8_t* out) {
    assert(message->base.descriptor == &game_state__descriptor);
    return protobuf_c_message_pack((const ProtobufCMessage*) message, out);
}
size_t game_state__pack_to_buffer(const GameState* message,
                                  ProtobufCBuffer* buffer) {
    assert(message->base.descriptor == &game_state__descriptor);
    return protobuf_c_message_pack_to_buffer((const ProtobufCMessage*) message, buffer);
}
GameState*
game_state__unpack(ProtobufCAllocator* allocator,
                   size_t len,
                   const uint8_t* data) {
    return (GameState*)
        protobuf_c_message_unpack(&game_state__descriptor,
                                  allocator, len, data);
}
void game_state__free_unpacked(GameState* message,
                               ProtobufCAllocator* allocator) {
    if (!message)
        return;
    assert(message->base.descriptor == &game_state__descriptor);
    protobuf_c_message_free_unpacked((ProtobufCMessage*) message, allocator);
}
static const ProtobufCFieldDescriptor game_state__field_descriptors[1] =
    {
        {
            "state",
            1,
            PROTOBUF_C_LABEL_NONE,
            PROTOBUF_C_TYPE_ENUM,
            0, /* quantifier_offset */
            offsetof(GameState, state),
            &state__descriptor,
            NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
};
static const unsigned game_state__field_indices_by_name[] = {
    0, /* field[0] = state */
};
static const ProtobufCIntRange game_state__number_ranges[1 + 1] =
    {
        {1, 0},
        {0, 1}};
const ProtobufCMessageDescriptor game_state__descriptor =
    {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "GameState",
        "GameState",
        "GameState",
        "",
        sizeof(GameState),
        1,
        game_state__field_descriptors,
        game_state__field_indices_by_name,
        1, game_state__number_ranges,
        (ProtobufCMessageInit) game_state__init,
        NULL, NULL, NULL /* reserved[123] */
};
static const ProtobufCEnumValue state__enum_values_by_number[4] =
    {
        {"POISON_IVY", "STATE__POISON_IVY", 0},
        {"DEHYDRATION", "STATE__DEHYDRATION", 1},
        {"HYPOTHERMIA_START", "STATE__HYPOTHERMIA_START", 2},
        {"HYPOTHERMIA_END", "STATE__HYPOTHERMIA_END", 3},
};
static const ProtobufCIntRange state__value_ranges[] = {
    {0, 0}, {0, 4}};
static const ProtobufCEnumValueIndex state__enum_values_by_name[4] =
    {
        {"DEHYDRATION", 1},
        {"HYPOTHERMIA_END", 3},
        {"HYPOTHERMIA_START", 2},
        {"POISON_IVY", 0},
};
const ProtobufCEnumDescriptor state__descriptor =
    {
        PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
        "State",
        "State",
        "State",
        "",
        4,
        state__enum_values_by_number,
        4,
        state__enum_values_by_name,
        1,
        state__value_ranges,
        NULL, NULL, NULL, NULL /* reserved[1234] */
};
