/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gamepad.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gamepad.pb-c.h"
void   gp_state__init
                     (GpState         *message)
{
  static const GpState init_value = GP_STATE__INIT;
  *message = init_value;
}
size_t gp_state__get_packed_size
                     (const GpState *message)
{
  assert(message->base.descriptor == &gp_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gp_state__pack
                     (const GpState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gp_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gp_state__pack_to_buffer
                     (const GpState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gp_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GpState *
       gp_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GpState *)
     protobuf_c_message_unpack (&gp_state__descriptor,
                                allocator, len, data);
}
void   gp_state__free_unpacked
                     (GpState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gp_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor gp_state__field_descriptors[3] =
{
  {
    "connected",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(GpState, connected),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "buttons",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(GpState, buttons),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "axes",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(GpState, n_axes),
    offsetof(GpState, axes),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gp_state__field_indices_by_name[] = {
  2,   /* field[2] = axes */
  1,   /* field[1] = buttons */
  0,   /* field[0] = connected */
};
static const ProtobufCIntRange gp_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor gp_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GpState",
  "GpState",
  "GpState",
  "",
  sizeof(GpState),
  3,
  gp_state__field_descriptors,
  gp_state__field_indices_by_name,
  1,  gp_state__number_ranges,
  (ProtobufCMessageInit) gp_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
