/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: msg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "msg.pb-c.h"
void   msg_type__init
                     (MsgType         *message)
{
  static const MsgType init_value = MSG_TYPE__INIT;
  *message = init_value;
}
size_t msg_type__get_packed_size
                     (const MsgType *message)
{
  assert(message->base.descriptor == &msg_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg_type__pack
                     (const MsgType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg_type__pack_to_buffer
                     (const MsgType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MsgType *
       msg_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MsgType *)
     protobuf_c_message_unpack (&msg_type__descriptor,
                                allocator, len, data);
}
void   msg_type__free_unpacked
                     (MsgType *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor msg_type__field_descriptors[1] =
{
  {
    "msg",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(MsgType, msg),
    &msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg_type__field_indices_by_name[] = {
  0,   /* field[0] = msg */
};
static const ProtobufCIntRange msg_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor msg_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MsgType",
  "MsgType",
  "MsgType",
  "",
  sizeof(MsgType),
  1,
  msg_type__field_descriptors,
  msg_type__field_indices_by_name,
  1,  msg_type__number_ranges,
  (ProtobufCMessageInit) msg_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue msg__enum_values_by_number[5] =
{
  { "GAMEPAD_STATE", "MSG__GAMEPAD_STATE", 0 },
  { "DEVICE_DATA", "MSG__DEVICE_DATA", 1 },
  { "RUN_MODE", "MSG__RUN_MODE", 2 },
  { "CHALLENGE_RESULT", "MSG__CHALLENGE_RESULT", 3 },
  { "LOG", "MSG__LOG", 4 },
};
static const ProtobufCIntRange msg__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex msg__enum_values_by_name[5] =
{
  { "CHALLENGE_RESULT", 3 },
  { "DEVICE_DATA", 1 },
  { "GAMEPAD_STATE", 0 },
  { "LOG", 4 },
  { "RUN_MODE", 2 },
};
const ProtobufCEnumDescriptor msg__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Msg",
  "Msg",
  "Msg",
  "",
  5,
  msg__enum_values_by_number,
  5,
  msg__enum_values_by_name,
  1,
  msg__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
