/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: msg.proto */

#ifndef PROTOBUF_C_msg_2eproto__INCLUDED
#define PROTOBUF_C_msg_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _MsgType MsgType;


/* --- enums --- */

typedef enum _Msg {
  MSG__GAMEPAD_STATE = 0,
  MSG__DEVICE_DATA = 1,
  MSG__RUN_MODE = 2,
  MSG__CHALLENGE_RESULT = 3,
  MSG__LOG = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MSG)
} Msg;

/* --- messages --- */

struct  _MsgType
{
  ProtobufCMessage base;
  Msg msg;
};
#define MSG_TYPE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&msg_type__descriptor) \
    , MSG__GAMEPAD_STATE }


/* MsgType methods */
void   msg_type__init
                     (MsgType         *message);
size_t msg_type__get_packed_size
                     (const MsgType   *message);
size_t msg_type__pack
                     (const MsgType   *message,
                      uint8_t             *out);
size_t msg_type__pack_to_buffer
                     (const MsgType   *message,
                      ProtobufCBuffer     *buffer);
MsgType *
       msg_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   msg_type__free_unpacked
                     (MsgType *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MsgType_Closure)
                 (const MsgType *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    msg__descriptor;
extern const ProtobufCMessageDescriptor msg_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_msg_2eproto__INCLUDED */
