/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: startpos.proto */

#ifndef PROTOBUF_C_startpos_2eproto__INCLUDED
#define PROTOBUF_C_startpos_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _StartPos StartPos;


/* --- enums --- */

typedef enum _Pos {
  POS__LEFT = 0,
  POS__RIGHT = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(POS)
} Pos;

/* --- messages --- */

struct  _StartPos
{
  ProtobufCMessage base;
  Pos pos;
};
#define START_POS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&start_pos__descriptor) \
    , POS__LEFT }


/* StartPos methods */
void   start_pos__init
                     (StartPos         *message);
size_t start_pos__get_packed_size
                     (const StartPos   *message);
size_t start_pos__pack
                     (const StartPos   *message,
                      uint8_t             *out);
size_t start_pos__pack_to_buffer
                     (const StartPos   *message,
                      ProtobufCBuffer     *buffer);
StartPos *
       start_pos__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   start_pos__free_unpacked
                     (StartPos *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*StartPos_Closure)
                 (const StartPos *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    pos__descriptor;
extern const ProtobufCMessageDescriptor start_pos__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_startpos_2eproto__INCLUDED */
