/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: start_pos.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "start_pos.pb-c.h"
void start_pos__init(StartPos* message) {
    static const StartPos init_value = START_POS__INIT;
    *message = init_value;
}
size_t start_pos__get_packed_size(const StartPos* message) {
    assert(message->base.descriptor == &start_pos__descriptor);
    return protobuf_c_message_get_packed_size((const ProtobufCMessage*) (message));
}
size_t start_pos__pack(const StartPos* message,
                       uint8_t* out) {
    assert(message->base.descriptor == &start_pos__descriptor);
    return protobuf_c_message_pack((const ProtobufCMessage*) message, out);
}
size_t start_pos__pack_to_buffer(const StartPos* message,
                                 ProtobufCBuffer* buffer) {
    assert(message->base.descriptor == &start_pos__descriptor);
    return protobuf_c_message_pack_to_buffer((const ProtobufCMessage*) message, buffer);
}
StartPos*
start_pos__unpack(ProtobufCAllocator* allocator,
                  size_t len,
                  const uint8_t* data) {
    return (StartPos*)
        protobuf_c_message_unpack(&start_pos__descriptor,
                                  allocator, len, data);
}
void start_pos__free_unpacked(StartPos* message,
                              ProtobufCAllocator* allocator) {
    if (!message)
        return;
    assert(message->base.descriptor == &start_pos__descriptor);
    protobuf_c_message_free_unpacked((ProtobufCMessage*) message, allocator);
}
static const ProtobufCFieldDescriptor start_pos__field_descriptors[1] =
    {
        {
            "pos",
            1,
            PROTOBUF_C_LABEL_NONE,
            PROTOBUF_C_TYPE_ENUM,
            0, /* quantifier_offset */
            offsetof(StartPos, pos),
            &pos__descriptor,
            NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
};
static const unsigned start_pos__field_indices_by_name[] = {
    0, /* field[0] = pos */
};
static const ProtobufCIntRange start_pos__number_ranges[1 + 1] =
    {
        {1, 0},
        {0, 1}};
const ProtobufCMessageDescriptor start_pos__descriptor =
    {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "StartPos",
        "StartPos",
        "StartPos",
        "",
        sizeof(StartPos),
        1,
        start_pos__field_descriptors,
        start_pos__field_indices_by_name,
        1, start_pos__number_ranges,
        (ProtobufCMessageInit) start_pos__init,
        NULL, NULL, NULL /* reserved[123] */
};
static const ProtobufCEnumValue pos__enum_values_by_number[2] =
    {
        {"LEFT", "POS__LEFT", 0},
        {"RIGHT", "POS__RIGHT", 1},
};
static const ProtobufCIntRange pos__value_ranges[] = {
    {0, 0}, {0, 2}};
static const ProtobufCEnumValueIndex pos__enum_values_by_name[2] =
    {
        {"LEFT", 0},
        {"RIGHT", 1},
};
const ProtobufCEnumDescriptor pos__descriptor =
    {
        PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
        "Pos",
        "Pos",
        "Pos",
        "",
        2,
        pos__enum_values_by_number,
        2,
        pos__enum_values_by_name,
        1,
        pos__value_ranges,
        NULL, NULL, NULL, NULL /* reserved[1234] */
};
