/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: text.proto */

#ifndef PROTOBUF_C_text_2eproto__INCLUDED
#define PROTOBUF_C_text_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Text Text;


/* --- enums --- */


/* --- messages --- */

struct  _Text
{
  ProtobufCMessage base;
  /*
   *CHALLENGE_DATA: initial values or results of challenges
   */
  size_t n_payload;
  char **payload;
};
#define TEXT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&text__descriptor) \
    , 0,NULL }


/* Text methods */
void   text__init
                     (Text         *message);
size_t text__get_packed_size
                     (const Text   *message);
size_t text__pack
                     (const Text   *message,
                      uint8_t             *out);
size_t text__pack_to_buffer
                     (const Text   *message,
                      ProtobufCBuffer     *buffer);
Text *
       text__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   text__free_unpacked
                     (Text *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Text_Closure)
                 (const Text *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor text__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_text_2eproto__INCLUDED */
