site_name: Pioneers in Engineering Documentation
site_url: https://example.com/
site_author: Ian Leung
nav:
  # introduction
  - Home: 'index.md'
  # starting your first robot
  - Connecting To Your Robot: 'dawn_quickstart.md'
  # kit extension
  - Dawn Tutorial: 'dawn_quickstart.md'
  # software stuff
  - Your First Program: 'first_program.md'
  - API Reference: 'api.md'
  - Device Get: 'device_get.md'
  - Device Set: 'device_set.md'

theme: readthedocs
# to start this server cd into docs and use `mkdocs serve`