site_name: Pioneers in Engineering Documentation
site_url: https://example.com/
site_author: Ian Leung
nav:
  #introductions
  - Home: 'index.md'
  #starting your first robot
  - Building Your First Robot:
  - Base Kit Manual: 
  - Software:
  - Dawn Tutorial: 
  - Quickstart Guide:
  #software stuff
  - Getting Started:
  - Your First Program:
    -
  - API Refrence: 'api.md'
  - Devices:
    - Devices: 'device.md'
    - Device Get: 'device_get.md'
    - Device Set: 'device_set.md'

theme: readthedocs
#to start this server cd into docs and use `mkdocs serve`